[package]
name = "rust-mpi-adder-binding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpi = { version = "0.6", features = ["user-operations", "derive"] }
mpi-sys = "0.2"
libc = "0.2"
